apiVersion: v1
kind: Service
metadata:
  name: democrp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: democrp-service
  sessionAffinity: None
  type: ClusterIP
