name: Push image to GCR
on:
  push:
    branches: [ main ]
jobs:
  pull-push-gcr:
    name: Pull image and push it to GCR (to test for errors)
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pwstaging/demo-crm
      PROJECT_ID: gilad-dev-k8s
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v1
      with:
          export_default_credentials: true
    - name: Pull docker image 
      run: docker pull $IMAGE_NAME

    - uses: google-github-actions/auth@v1
      with:
         service_account: github-actions@gilad-dev-k8s.iam.gserviceaccount.com
         credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY}}

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker image to GCR
      env: 
        GIT_TAG: v0.1.0
      run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG



#name: Terraform Automate
#on:
  #push:
    #branches: [ main ]
  #jobs:
    #auto-tf:
      #name: Automate the terraform lifecycle on the provided files
      